version: '3.2'

services:
  site:
    build:
      context: .
      dockerfile: Dockerfile
      ssh:
        - default
    command: bundle exec jekyll serve --host "0.0.0.0"
    ports:
      - '4000:4000'
    volumes:
      - .:/blog
